-- ╔══════════════════════════════════════════════════════════════╗
-- ║  Seed: Família Champalimaud (gerado de src/data/mockData.js)    ║
-- ║  SUBSTITUIÇÃO COMPLETA — apaga e reinsere tudo. Correr no SQL    ║
-- ║  Editor depois do schema.sql. Pode ser corrido vezes sem conta. ║
-- ╚══════════════════════════════════════════════════════════════╝

-- garante a coluna is_primary (caso o schema tenha sido criado antes)
alter table public.relationships add column if not exists is_primary boolean not null default true;

-- limpa os dados antigos (mantém as tabelas e políticas)
delete from public.relationships;
delete from public.memories;
delete from public.members;

insert into public.members (id, name, nickname, generation) values
  ('ping', 'Ping', 'T-Rex Gregossauro', 1),
  ('jajonhe', 'Jajonhe', 'Tropas', 1),
  ('grizo', 'Grizo', 'Burlão', 1),
  ('hugo', 'Hugo', 'Donald', 1),
  ('carvalheira', 'Carvalheira', 'Mãe Estou Solteiro', 2),
  ('gomes', 'Gomes', 'O Incrível Hulkoiro', 2),
  ('piri', 'Piri', null, 2),
  ('bras', 'Brás', 'Morcelas', 2),
  ('clara', 'Clara', 'Pardalita', 2),
  ('ze_cordeiro', 'Zé Cordeiro', 'Zé Curriqueiro Follow The Leader', 2),
  ('pedro', 'Pedro', 'Edro', 2),
  ('vartels', 'Vartels', 'Tintim', 3),
  ('joao_dias', 'João Dias', 'Rocha Mole', 3),
  ('gabriel', 'Gabriel', 'Picha', 3),
  ('moguels', 'Moguels', 'Vaquinha', 3),
  ('caco', 'Caço', 'Setaque', 3),
  ('carmo', 'Carmo', 'Ca...Clara', 4),
  ('vaz', 'Vaz', 'Sou-Bi-Ónico', 4),
  ('maria_castro', 'Maria Castro', null, 4),
  ('matilde_neves', 'Matilde Neves', 'Apóstolo 12 e Meio', 4),
  ('ines_costa', 'Inês Costa', 'Fábio Coentrão', 4),
  ('sofia_pascoa', 'Sofia Páscoa', null, 4),
  ('migueleo', 'Migueleo', 'Miguélio 50 Pontos', 3),
  ('tildes', 'Matilde', 'Inspetora Mini', 3),
  ('bia_l', 'Bia Landeiro', null, 3),
  ('marta', 'Marta', null, 3),
  ('pippo', 'Pippo', 'Triângulo Otis', 3),
  ('leti', 'Letícia', 'Lanches', 4),
  ('matilde_alves', 'Matilde', 'A Falhada', 4),
  ('kika_rocha', 'Kika Rocha', null, 4),
  ('mini_rita', 'Mini Rita', 'Kréu', 4),
  ('rui_jorge', 'Rui Jorge', 'Dora', 2),
  ('vasco', 'Vasco', 'Isqueiro', 2),
  ('rodolfo', 'Rodolfo', 'Comilão', 2),
  ('cesar', 'César', 'Inem', 2),
  ('maria_p', 'Maria P.', 'Delay', 2),
  ('tommy', 'Tommy', 'Eminem da Praxe', 3),
  ('mike', 'Mike', 'GPS', 3),
  ('sassa', 'Sassa', 'MC Completo', 4),
  ('mota', 'Mota', 'Angélico', 4),
  ('munha', 'Munhá', 'Varão', 2),
  ('ximenes', 'Ximenes', 'Palma Bigots X-Men Calvo', 2),
  ('henrique', 'Henrique', 'Phenrique', 2),
  ('maria_costa', 'Maria Costa', null, 2),
  ('andreia', 'Andreia', 'Kréu', 2),
  ('tomas_h', 'Tomás H.', 'Grito', 3),
  ('maravilha', 'Maravilha', 'Pirata Rabolho', 3),
  ('sissi', 'Sissi', null, 3),
  ('gabi', 'Gabi', 'Camões', 3),
  ('carol', 'Carol', 'Letxícia', 3),
  ('dinis', 'Dinis', 'Charlotte', 3),
  ('joana', 'Joana', 'Bombas', 3),
  ('susi', 'Susi', 'Fiambre d''Atum', 4),
  ('tomas_m', 'Tomás M.', 'Caloirinho D.T.T.', 4),
  ('nanda', 'Nanda', 'A Careca dum Calvo que Parece o Rabo dum Macaco', 3),
  ('raul', 'Raul', 'Maré', 5),
  ('rita_pais', 'Rita Pais', 'Padeira de Campolide de Gelatina Quedas Torera', 4),
  ('eva', 'Eva', 'Eva Gina Flor', 4),
  ('sara', 'Sara', 'Ladrona Ultras Autotuna', 4),
  ('sofia_l', 'Sofia', 'Sofia Solista', 4),
  ('tita', 'Tita', null, 4),
  ('morgana', 'Morgana', 'Unísono', 4),
  ('ana', 'Ana', null, 3),
  ('luisa', 'Luísa', 'Monstrinho do Álcool', 3),
  ('neves', 'Neves', 'Caloiro 123', 5),
  ('barriga', 'Barriga', 'Belly''s', 3),
  ('joaozinho', 'Joãozinho', 'Joãozinho Joãozinho Joãozinho', 5),
  ('rui_g', 'Rui Guedes', 'Machupão Alfa', 3),
  ('catarina', 'Catarina', 'Kirk Kat', 5),
  ('estrela', 'Estrela', 'O Máiore', 5),
  ('porto', 'Porto', 'Sou um Piço', 4),
  ('tiago_soares', 'Tiago Soares', null, 5),
  ('maquina', 'Máquina', 'Máquina do Álcool', 5),
  ('matilde_roque', 'Matilde Roque', null, 5),
  ('timi', 'Timi', 'Perna de Pau Médio Mal Passado', 5),
  ('matilde_conde', 'Matilde Conde', 'Macaquinha das Badtrips', 5),
  ('martina', 'Martina', 'Martini', 5),
  ('kika_moreira', 'Kika Moreira', null, 4),
  ('guilherme', 'Gui Gomes', 'Caloiro do Coito', 3),
  ('laura', 'Laura', 'Petite Girly Pop', 3),
  ('leonor_mendes', 'Leonor Mendes', 'Caloirra Frrancesa', 2),
  ('rita_c', 'Rita Correia', 'Frigorífico', 3),
  ('gui_s', 'Gui Santos', 'Guilidades o Caloiro Amor da Minha Vida', 3),
  ('binga', 'Binga', 'Chambingo', 3),
  ('ines_a', 'Inês Alvelos', 'Jonick', 3),
  ('raquel', 'Raquel', 'Minar-te-ei', 4),
  ('ines_barbeiro', 'Inês Barbeiro', null, 4),
  ('leonor_catarino', 'Leonor Catarino', 'Octavia', 4);

insert into public.relationships (id, parent_id, child_id, type, is_primary) values
  ('r-ping-carvalheira', 'ping', 'carvalheira', 'padrinho', true),
  ('r-ping-gomes', 'ping', 'gomes', 'padrinho', true),
  ('r-jajonhe-gomes', 'jajonhe', 'gomes', 'padrinho', false),
  ('r-jajonhe-piri', 'jajonhe', 'piri', 'padrinho', true),
  ('r-jajonhe-bras', 'jajonhe', 'bras', 'padrinho', true),
  ('r-jajonhe-clara', 'jajonhe', 'clara', 'padrinho', true),
  ('r-jajonhe-ze_cordeiro', 'jajonhe', 'ze_cordeiro', 'padrinho', true),
  ('r-jajonhe-pedro', 'jajonhe', 'pedro', 'padrinho', true),
  ('r-gomes-vartels', 'gomes', 'vartels', 'padrinho', true),
  ('r-gomes-joao_dias', 'gomes', 'joao_dias', 'padrinho', true),
  ('r-gomes-gabriel', 'gomes', 'gabriel', 'padrinho', true),
  ('r-piri-moguels', 'piri', 'moguels', 'madrinha', true),
  ('r-bras-moguels', 'bras', 'moguels', 'padrinho', false),
  ('r-bras-caco', 'bras', 'caco', 'padrinho', true),
  ('r-vartels-carmo', 'vartels', 'carmo', 'padrinho', true),
  ('r-maria_costa-carmo', 'maria_costa', 'carmo', 'madrinha', false),
  ('r-joao_dias-vaz', 'joao_dias', 'vaz', 'padrinho', true),
  ('r-joao_dias-maria_castro', 'joao_dias', 'maria_castro', 'padrinho', true),
  ('r-joao_dias-matilde_neves', 'joao_dias', 'matilde_neves', 'padrinho', true),
  ('r-moguels-ines_costa', 'moguels', 'ines_costa', 'padrinho', true),
  ('r-caco-sofia_pascoa', 'caco', 'sofia_pascoa', 'padrinho', true),
  ('r-clara-migueleo', 'clara', 'migueleo', 'madrinha', true),
  ('r-clara-tildes', 'clara', 'tildes', 'madrinha', true),
  ('r-clara-bia_l', 'clara', 'bia_l', 'madrinha', true),
  ('r-clara-marta', 'clara', 'marta', 'madrinha', true),
  ('r-clara-pippo', 'clara', 'pippo', 'madrinha', true),
  ('r-clara-ana', 'clara', 'ana', 'madrinha', true),
  ('r-clara-luisa', 'clara', 'luisa', 'madrinha', true),
  ('r-clara-laura', 'clara', 'laura', 'madrinha', true),
  ('r-clara-nanda', 'clara', 'nanda', 'madrinha', true),
  ('r-leti-nanda', 'leti', 'nanda', 'madrinha', false),
  ('r-tildes-leti', 'tildes', 'leti', 'madrinha', true),
  ('r-marta-matilde_alves', 'marta', 'matilde_alves', 'madrinha', true),
  ('r-marta-kika_rocha', 'marta', 'kika_rocha', 'madrinha', true),
  ('r-pippo-mini_rita', 'pippo', 'mini_rita', 'padrinho', true),
  ('r-tommy-mini_rita', 'tommy', 'mini_rita', 'padrinho', false),
  ('r-grizo-rui_jorge', 'grizo', 'rui_jorge', 'padrinho', true),
  ('r-grizo-vasco', 'grizo', 'vasco', 'padrinho', true),
  ('r-grizo-rodolfo', 'grizo', 'rodolfo', 'padrinho', true),
  ('r-grizo-cesar', 'grizo', 'cesar', 'padrinho', true),
  ('r-grizo-leonor_mendes', 'grizo', 'leonor_mendes', 'padrinho', true),
  ('r-grizo-maria_p', 'grizo', 'maria_p', 'padrinho', true),
  ('r-henrique-maria_p', 'henrique', 'maria_p', 'padrinho', false),
  ('r-vasco-tommy', 'vasco', 'tommy', 'padrinho', true),
  ('r-rodolfo-mike', 'rodolfo', 'mike', 'padrinho', true),
  ('r-mike-sassa', 'mike', 'sassa', 'padrinho', true),
  ('r-mike-mota', 'mike', 'mota', 'padrinho', true),
  ('r-maravilha-mota', 'maravilha', 'mota', 'padrinho', false),
  ('r-cesar-carol', 'cesar', 'carol', 'padrinho', true),
  ('r-cesar-dinis', 'cesar', 'dinis', 'padrinho', true),
  ('r-cesar-joana', 'cesar', 'joana', 'padrinho', true),
  ('r-cesar-guilherme', 'cesar', 'guilherme', 'padrinho', true),
  ('r-hugo-munha', 'hugo', 'munha', 'padrinho', true),
  ('r-hugo-ximenes', 'hugo', 'ximenes', 'padrinho', true),
  ('r-hugo-henrique', 'hugo', 'henrique', 'padrinho', true),
  ('r-hugo-maria_costa', 'hugo', 'maria_costa', 'padrinho', true),
  ('r-hugo-andreia', 'hugo', 'andreia', 'padrinho', true),
  ('r-henrique-tomas_h', 'henrique', 'tomas_h', 'padrinho', true),
  ('r-henrique-maravilha', 'henrique', 'maravilha', 'padrinho', true),
  ('r-maria_costa-sissi', 'maria_costa', 'sissi', 'madrinha', true),
  ('r-andreia-gabi', 'andreia', 'gabi', 'madrinha', true),
  ('r-maravilha-susi', 'maravilha', 'susi', 'padrinho', true),
  ('r-maravilha-tomas_m', 'maravilha', 'tomas_m', 'padrinho', true),
  ('r-maravilha-sara', 'maravilha', 'sara', 'padrinho', true),
  ('r-vaz-raul', 'vaz', 'raul', 'padrinho', true),
  ('r-vaz-joaozinho', 'vaz', 'joaozinho', 'padrinho', true),
  ('r-ines_a-rita_pais', 'ines_a', 'rita_pais', 'madrinha', true),
  ('r-leonor_mendes-rita_pais', 'leonor_mendes', 'rita_pais', 'madrinha', false),
  ('r-rui_jorge-barriga', 'rui_jorge', 'barriga', 'padrinho', true),
  ('r-ines_a-barriga', 'ines_a', 'barriga', 'madrinha', false),
  ('r-rui_jorge-rui_g', 'rui_jorge', 'rui_g', 'padrinho', true),
  ('r-migueleo-eva', 'migueleo', 'eva', 'padrinho', true),
  ('r-rita_c-sofia_l', 'rita_c', 'sofia_l', 'madrinha', true),
  ('r-rita_c-tita', 'rita_c', 'tita', 'madrinha', true),
  ('r-gabi-morgana', 'gabi', 'morgana', 'madrinha', true),
  ('r-sassa-neves', 'sassa', 'neves', 'padrinho', true),
  ('r-matilde_neves-catarina', 'matilde_neves', 'catarina', 'madrinha', true),
  ('r-matilde_neves-estrela', 'matilde_neves', 'estrela', 'madrinha', true),
  ('r-joao_dias-porto', 'joao_dias', 'porto', 'padrinho', true),
  ('r-maria_castro-porto', 'maria_castro', 'porto', 'madrinha', false),
  ('r-sofia_pascoa-tiago_soares', 'sofia_pascoa', 'tiago_soares', 'madrinha', true),
  ('r-sofia_pascoa-matilde_conde', 'sofia_pascoa', 'matilde_conde', 'madrinha', true),
  ('r-mota-maquina', 'mota', 'maquina', 'padrinho', true),
  ('r-susi-matilde_roque', 'susi', 'matilde_roque', 'madrinha', true),
  ('r-piri-matilde_roque', 'piri', 'matilde_roque', 'madrinha', false),
  ('r-carmo-timi', 'carmo', 'timi', 'madrinha', true),
  ('r-leti-martina', 'leti', 'martina', 'madrinha', true),
  ('r-laura-kika_moreira', 'laura', 'kika_moreira', 'madrinha', true),
  ('r-leonor_mendes-rita_c', 'leonor_mendes', 'rita_c', 'madrinha', true),
  ('r-leonor_mendes-gui_s', 'leonor_mendes', 'gui_s', 'madrinha', true),
  ('r-leonor_mendes-binga', 'leonor_mendes', 'binga', 'madrinha', true),
  ('r-leonor_mendes-ines_a', 'leonor_mendes', 'ines_a', 'madrinha', true),
  ('r-binga-raquel', 'binga', 'raquel', 'madrinha', true),
  ('r-caco-ines_barbeiro', 'caco', 'ines_barbeiro', 'padrinho', true),
  ('r-joana-leonor_catarino', 'joana', 'leonor_catarino', 'madrinha', true);
