-- ╔══════════════════════════════════════════════════════════════╗
-- ║  Seed: Família Champalimaud (gerado de src/data/mockData.js)    ║
-- ╚══════════════════════════════════════════════════════════════╝
-- Correr DEPOIS de schema.sql. Idempotente (on conflict do update/nothing).

insert into public.members (id, name, nickname, generation, photo_url, course, faculty, year_joined, email, bio, quote) values
  ('ping', 'Ping', 'T-Rex Gregossauro', 0, null, null, null, null, null, null, null),
  ('jajonhe', 'Jajonhe', 'Tropas', 0, null, null, null, null, null, null, null),
  ('grizo', 'Grizo', 'Burlão', 0, null, null, null, null, null, null, null),
  ('hugo', 'Hugo', 'Donald', 0, null, null, null, null, null, null, null),
  ('vasco', 'Vasco', 'Isqueiro', 0, null, null, null, null, null, null, null),
  ('leonor_mendes', 'Leonor Mendes', 'Caloirra Frrancesa', 0, null, null, null, null, null, null, null),
  ('rui_jorge', 'Rui Jorge', 'Dora', 0, null, null, null, null, null, null, null),
  ('cesar', 'César', 'Inem', 0, null, null, null, null, null, null, null),
  ('rodolfo', 'Rodolfo', 'Comilão', 0, null, null, null, null, null, null, null),
  ('carvalheira', 'Carvalheira', 'Mãe Estou Solteiro', 1, null, null, null, null, null, null, null),
  ('gomes', 'Gomes', 'O Incrível Hulkoiro', 1, null, null, null, null, null, null, null),
  ('ze_cordeiro', 'Zé Cordeiro', 'Zé Curriqueiro Follow The Leader', 1, null, null, null, null, null, null, null),
  ('gabriel', 'Gabriel', 'Picha', 2, null, null, null, null, null, null, null),
  ('joao_dias', 'João Dias', 'Rocha Mole', 2, null, null, null, null, null, null, null),
  ('vartels', 'Vartels', 'Tintim', 2, null, null, null, null, null, null, null),
  ('vaz', 'Vaz', 'Sou-Bi-Ónico', 3, null, null, null, null, null, null, null),
  ('matilde_neves', 'Matilde Neves', 'Apóstolo 12 e Meio', 3, null, null, null, null, null, null, null),
  ('maria_castro', 'Maria Castro', null, 3, null, null, null, null, null, null, null),
  ('raul', 'Raul', 'Maré', 4, null, null, null, null, null, null, null),
  ('joaozinho', 'Joãozinho', 'Joãozinho Joãozinho Joãozinho', 4, null, null, null, null, null, null, null),
  ('porto', 'Porto', 'Sou um Piço', 4, null, null, null, null, null, null, null),
  ('catarina', 'Catarina', 'Kirk Kat', 5, null, null, null, null, null, null, null),
  ('estrela', 'Estrela', 'O Máiore', 5, null, null, null, null, null, null, null),
  ('piri', 'Piri', null, 1, null, null, null, null, null, null, null),
  ('bras', 'Brás', 'Morcelas', 1, null, null, null, null, null, null, null),
  ('pedro', 'Pedro', 'Edro', 1, null, null, null, null, null, null, null),
  ('clara', 'Clara', 'Pardalita', 1, null, null, null, null, null, null, null),
  ('moguels', 'Moguels', 'Vaquinha', 2, null, null, null, null, null, null, null),
  ('caco', 'Caço', 'Setaque', 2, null, null, null, null, null, null, null),
  ('ines_costa', 'Inês Costa', 'Fábio Coentrão', 3, null, null, null, null, null, null, null),
  ('sofia_pascoa', 'Sofia Páscoa', null, 3, null, null, null, null, null, null, null),
  ('ines_barbeiro', 'Inês Barbeiro', null, 3, null, null, null, null, null, null, null),
  ('matilde_conde', 'Matilde Conde', 'Macaquinha das Badtrips', 4, null, null, null, null, null, null, null),
  ('tiago_soares', 'Tiago Soares', null, 4, null, null, null, null, null, null, null),
  ('migueleo', 'Migueleo', 'Miguélio 50 Pontos', 5, null, null, null, null, null, null, null),
  ('laura', 'Laura', 'Petite Girly Pop', 5, null, null, null, null, null, null, null),
  ('tildes', 'Tildes', 'Inspetora Mini', 5, null, null, null, null, null, null, null),
  ('bia_l', 'Bia L.', null, 5, null, null, null, null, null, null, null),
  ('marta', 'Marta', null, 5, null, null, null, null, null, null, null),
  ('pippo', 'Pippo', 'Triângulo Otis', 5, null, null, null, null, null, null, null),
  ('eva', 'Eva', 'Eva Gina Flor', 6, null, null, null, null, null, null, null),
  ('matilde_roque', 'Matilde Roque', null, 6, null, null, null, null, null, null, null),
  ('ana', 'Ana', null, 6, null, null, null, null, null, null, null),
  ('kika_moreira', 'Kika Moreira', null, 6, null, null, null, null, null, null, null),
  ('martina', 'Martina', 'Martini', 6, null, null, null, null, null, null, null),
  ('leti', 'Leti', 'Lanches', 6, null, null, null, null, null, null, null),
  ('nanda', 'Nanda', 'A Careca dum Calvo que Parece o Rabo dum Macaco', 7, null, null, null, null, null, null, null),
  ('matilde_alves', 'Matilde Alves', 'Karpa Flávia: A Falhada', 6, null, null, null, null, null, null, null),
  ('kika_rocha', 'Kika Rocha', null, 6, null, null, null, null, null, null, null),
  ('luisa', 'Luísa', 'Monstrinho do Álcool', 6, null, null, null, null, null, null, null),
  ('mini_rita', 'Mini Rita', 'Kréu', 6, null, null, null, null, null, null, null),
  ('tommy', 'Tommy / Tomé', 'Eminem da Praxe', 1, null, null, null, null, null, null, null),
  ('gui_s', 'Gui S.', 'Guilidades o Caloiro Amor da Minha Vida', 1, null, null, null, null, null, null, null),
  ('binga', 'Binga', 'Chambingo', 1, null, null, null, null, null, null, null),
  ('rita_c', 'Rita C.', 'Frigorífico', 1, null, null, null, null, null, null, null),
  ('ines_a', 'Inês A.', 'Jonick', 1, null, null, null, null, null, null, null),
  ('raquel', 'Raquel', 'Minar-te-ei', 2, null, null, null, null, null, null, null),
  ('tita', 'Tita', null, 2, null, null, null, null, null, null, null),
  ('sofia_l', 'Sofia L.', 'Sofia Solista', 2, null, null, null, null, null, null, null),
  ('rita_pais', 'Rita Pais', 'Padeira de Campolide de Gelatina Quedas Torera', 2, null, null, null, null, null, null, null),
  ('barriga', 'Barriga', 'Belly''s', 2, null, null, null, null, null, null, null),
  ('rui_g', 'Rui G.', 'Machupão Alfa', 3, null, null, null, null, null, null, null),
  ('carol', 'Carol', 'Letxícia', 4, null, null, null, null, null, null, null),
  ('joana', 'Joana', 'Bombas', 4, null, null, null, null, null, null, null),
  ('dinis', 'Dinis', 'Charlotte', 4, null, null, null, null, null, null, null),
  ('guilherme', 'Guilherme', 'Caloiro do Coito', 5, null, null, null, null, null, null, null),
  ('leonor_catarino', 'Leonor Catarino', 'Octavia', 5, null, null, null, null, null, null, null),
  ('mike', 'Mike', 'GPS', 1, null, null, null, null, null, null, null),
  ('sassa', 'Sassa', 'MC Completo', 1, null, null, null, null, null, null, null),
  ('mota', 'Mota', 'Angélico', 1, null, null, null, null, null, null, null),
  ('neves', 'Neves', 'Caloiro 123', 2, null, null, null, null, null, null, null),
  ('maquina', 'Máquina', 'Máquina do Álcool', 2, null, null, null, null, null, null, null),
  ('munha', 'Munhá', 'Varão', 1, null, null, null, null, null, null, null),
  ('henrique', 'Henrique', 'Phenrique', 1, null, null, null, null, null, null, null),
  ('maria_p', 'Maria P.', 'Delay', 2, null, null, null, null, null, null, null),
  ('maravilha', 'Maravilha', 'Pirata Rabolho', 2, null, null, null, null, null, null, null),
  ('tomas_h', 'Tomás H.', 'Grito', 2, null, null, null, null, null, null, null),
  ('susi', 'Susi', 'Fiambre d''Atum', 2, null, null, null, null, null, null, null),
  ('tomas_m', 'Tomás M.', 'Caloirinho D.T.T.', 2, null, null, null, null, null, null, null),
  ('gabi', 'Gabi', 'Camões', 3, null, null, null, null, null, null, null),
  ('sara', 'Sara', 'Ladrona Ultras Autotuna', 3, null, null, null, null, null, null, null),
  ('morgana', 'Morgana', 'Unísono', 3, null, null, null, null, null, null, null),
  ('andreia', 'Andreia', 'Kréu', 1, null, null, null, null, null, null, null),
  ('maria', 'Maria', null, 1, null, null, null, null, null, null, null),
  ('ximenes', 'Ximenes', 'Palma Bigots X-Men Calvo', 1, null, null, null, null, null, null, null),
  ('sissi', 'Sissi', null, 2, null, null, null, null, null, null, null),
  ('carmo', 'Carmo', 'Ca...Clara', 2, null, null, null, null, null, null, null),
  ('timi', 'Timi', 'Perna de Pau Médio Mal Passado', 3, null, null, null, null, null, null, null)
on conflict (id) do update set
  name = excluded.name, nickname = excluded.nickname, generation = excluded.generation;

insert into public.relationships (id, parent_id, child_id, type) values
  ('r-ping-carvalheira', 'ping', 'carvalheira', 'padrinho'),
  ('r-ping-gomes', 'ping', 'gomes', 'padrinho'),
  ('r-ping-ze_cordeiro', 'ping', 'ze_cordeiro', 'padrinho'),
  ('r-gomes-gabriel', 'gomes', 'gabriel', 'padrinho'),
  ('r-gomes-joao_dias', 'gomes', 'joao_dias', 'padrinho'),
  ('r-ze_cordeiro-vartels', 'ze_cordeiro', 'vartels', 'padrinho'),
  ('r-joao_dias-vaz', 'joao_dias', 'vaz', 'padrinho'),
  ('r-joao_dias-matilde_neves', 'joao_dias', 'matilde_neves', 'padrinho'),
  ('r-joao_dias-maria_castro', 'joao_dias', 'maria_castro', 'padrinho'),
  ('r-vaz-raul', 'vaz', 'raul', 'padrinho'),
  ('r-vaz-joaozinho', 'vaz', 'joaozinho', 'padrinho'),
  ('r-matilde_neves-porto', 'matilde_neves', 'porto', 'madrinha'),
  ('r-porto-catarina', 'porto', 'catarina', 'padrinho'),
  ('r-porto-estrela', 'porto', 'estrela', 'padrinho'),
  ('r-jajonhe-piri', 'jajonhe', 'piri', 'padrinho'),
  ('r-jajonhe-bras', 'jajonhe', 'bras', 'padrinho'),
  ('r-jajonhe-pedro', 'jajonhe', 'pedro', 'padrinho'),
  ('r-jajonhe-clara', 'jajonhe', 'clara', 'padrinho'),
  ('r-piri-moguels', 'piri', 'moguels', 'padrinho'),
  ('r-piri-caco', 'piri', 'caco', 'padrinho'),
  ('r-moguels-ines_costa', 'moguels', 'ines_costa', 'padrinho'),
  ('r-caco-sofia_pascoa', 'caco', 'sofia_pascoa', 'padrinho'),
  ('r-caco-ines_barbeiro', 'caco', 'ines_barbeiro', 'padrinho'),
  ('r-ines_costa-matilde_conde', 'ines_costa', 'matilde_conde', 'madrinha'),
  ('r-ines_costa-tiago_soares', 'ines_costa', 'tiago_soares', 'madrinha'),
  ('r-matilde_conde-migueleo', 'matilde_conde', 'migueleo', 'madrinha'),
  ('r-matilde_conde-laura', 'matilde_conde', 'laura', 'madrinha'),
  ('r-matilde_conde-tildes', 'matilde_conde', 'tildes', 'madrinha'),
  ('r-tiago_soares-bia_l', 'tiago_soares', 'bia_l', 'padrinho'),
  ('r-tiago_soares-marta', 'tiago_soares', 'marta', 'padrinho'),
  ('r-tiago_soares-pippo', 'tiago_soares', 'pippo', 'padrinho'),
  ('r-migueleo-eva', 'migueleo', 'eva', 'padrinho'),
  ('r-migueleo-matilde_roque', 'migueleo', 'matilde_roque', 'padrinho'),
  ('r-migueleo-ana', 'migueleo', 'ana', 'padrinho'),
  ('r-laura-kika_moreira', 'laura', 'kika_moreira', 'madrinha'),
  ('r-laura-martina', 'laura', 'martina', 'madrinha'),
  ('r-tildes-leti', 'tildes', 'leti', 'madrinha'),
  ('r-leti-nanda', 'leti', 'nanda', 'madrinha'),
  ('r-bia_l-matilde_alves', 'bia_l', 'matilde_alves', 'madrinha'),
  ('r-marta-kika_rocha', 'marta', 'kika_rocha', 'madrinha'),
  ('r-marta-luisa', 'marta', 'luisa', 'madrinha'),
  ('r-pippo-mini_rita', 'pippo', 'mini_rita', 'padrinho'),
  ('r-vasco-tommy', 'vasco', 'tommy', 'padrinho'),
  ('r-vasco-gui_s', 'vasco', 'gui_s', 'padrinho'),
  ('r-leonor_mendes-binga', 'leonor_mendes', 'binga', 'madrinha'),
  ('r-leonor_mendes-rita_c', 'leonor_mendes', 'rita_c', 'madrinha'),
  ('r-leonor_mendes-ines_a', 'leonor_mendes', 'ines_a', 'madrinha'),
  ('r-binga-raquel', 'binga', 'raquel', 'padrinho'),
  ('r-rita_c-tita', 'rita_c', 'tita', 'madrinha'),
  ('r-rita_c-sofia_l', 'rita_c', 'sofia_l', 'madrinha'),
  ('r-ines_a-rita_pais', 'ines_a', 'rita_pais', 'madrinha'),
  ('r-ines_a-barriga', 'ines_a', 'barriga', 'madrinha'),
  ('r-barriga-rui_g', 'barriga', 'rui_g', 'padrinho'),
  ('r-rui_g-carol', 'rui_g', 'carol', 'padrinho'),
  ('r-rui_g-joana', 'rui_g', 'joana', 'padrinho'),
  ('r-rui_g-dinis', 'rui_g', 'dinis', 'padrinho'),
  ('r-dinis-guilherme', 'dinis', 'guilherme', 'padrinho'),
  ('r-dinis-leonor_catarino', 'dinis', 'leonor_catarino', 'padrinho'),
  ('r-rodolfo-mike', 'rodolfo', 'mike', 'padrinho'),
  ('r-rodolfo-sassa', 'rodolfo', 'sassa', 'padrinho'),
  ('r-rodolfo-mota', 'rodolfo', 'mota', 'padrinho'),
  ('r-sassa-neves', 'sassa', 'neves', 'padrinho'),
  ('r-mota-maquina', 'mota', 'maquina', 'padrinho'),
  ('r-grizo-munha', 'grizo', 'munha', 'padrinho'),
  ('r-grizo-henrique', 'grizo', 'henrique', 'padrinho'),
  ('r-munha-maria_p', 'munha', 'maria_p', 'padrinho'),
  ('r-henrique-maravilha', 'henrique', 'maravilha', 'padrinho'),
  ('r-henrique-tomas_h', 'henrique', 'tomas_h', 'padrinho'),
  ('r-henrique-susi', 'henrique', 'susi', 'padrinho'),
  ('r-henrique-tomas_m', 'henrique', 'tomas_m', 'padrinho'),
  ('r-tomas_h-gabi', 'tomas_h', 'gabi', 'padrinho'),
  ('r-tomas_m-sara', 'tomas_m', 'sara', 'padrinho'),
  ('r-tomas_m-morgana', 'tomas_m', 'morgana', 'padrinho'),
  ('r-hugo-andreia', 'hugo', 'andreia', 'padrinho'),
  ('r-hugo-maria', 'hugo', 'maria', 'padrinho'),
  ('r-hugo-ximenes', 'hugo', 'ximenes', 'padrinho'),
  ('r-maria-sissi', 'maria', 'sissi', 'madrinha'),
  ('r-ximenes-carmo', 'ximenes', 'carmo', 'padrinho'),
  ('r-carmo-timi', 'carmo', 'timi', 'madrinha')
on conflict (id) do nothing;
